name: aplikasi_bsu
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  http: ^1.1.0
  flutter_secure_storage: ^9.2.2

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  image_picker: ^1.0.7
  flutter_blue_plus: ^1.32.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
